id: A28CA5C7B
title: 'The Potent Nectar of Accomplishment: A Prayer and Supplication to the Vidyādhara
  Gurus of the Three Lineages'
type: translation
pechas:
- IB48F1E8F
- I9A12224E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:38:37.668554
  last_modified_at: 2023-01-04 11:38:37.668567
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IB48F1E8F/0BCF: 6F56
  I9A12224E/EA54: 6F56
